### PR TITLE
Get JupyterLab Server Tests working

### PR DESCRIPTION
**Pull request by Zsailer**

### CODE REVIEW

**Comment by Zsailer** [comment]
Looks like there is 1 flaky test on Window's 3.8

**Comment by echarles** [comment]
Thx @Zsailer . The GitHub CI has never been tested (not enable on jupyterlab repo). I can merge this PR when you feel it is ready. Just tell me.

**Comment by echarles** [comment]
In other words, Travis should be the reference.

**Comment by Zsailer** [comment]
Ok sounds good. I'm still working on the jupyterlab repo. Let's keep this open until I've stabilized over there. I'm updating this PR as I come across issues there.

**Comment by echarles** [comment]
The failure is related to the infamous Async py38.
I will merge and it could be fine with Travis.

**Comment by Zsailer** [comment]
Right. It's probably because we're using an old version of ipykernel in these test. I think we might need to switch to ipykernel source (i.e. master), rather that it's latest release.

**Pull request merged**
